[package]
name = "duckdns_updater"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Dustin Ryan-Roepsch"]

[profile.release]
lto = true
debug = true

[dependencies]
clokwerk = "0.3"
duckdns = "0.1"
