[package]
name = "duckdns_updater"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Dustin Ryan-Roepsch"]

[dependencies]
delay_timer = "0.10.1"
duckdns = "0.1"
futures = "0.3"
tokio = "1.15"
