[package]
name = "duckdns_updater"
version = "2.1.0"
edition = "2021"
license = "MIT"
authors = ["Dustin Ryan-Roepsch"]

[profile.release]
lto = true
debug = true

[dependencies]
anyhow = "1.0"
chrono = "0.4"
clokwerk = "0.3"
duckdns = "0.1"
log = "0.4"
simplelog = "0.11"
structopt = "0.3"